# Inserts list of contributors and community members into ./docs/credits.md
# Also generates an SVG showing all contributors, which is embedded into readme
name: 📊 Generate Contributor Credits
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:

  # Job #1 - Fetches sponsors and inserts into readme
  insert-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Generate Sponsors in Readme 💖
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          file: 'README.md'

  # Job #2 - Fetches contributors and inserts into readme
  insert-contributors:
    runs-on: ubuntu-latest
    name: Inserts contributors into credits.md
    steps:
    - name: Contribute List - Credits Page
      uses: akhilmhdh/contributors-readme-action@v2.2
      env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      with:
        image_size: 80
        readme_path: README.md
        columns_per_row: 6
        commit_message: ':purple_heart: Updates contributors list'
        committer_username: liss-bot
        committer_email: liss-bot@d0h.co
  
  # Job #3 - Generate an embedded SVG asset, showing all contributors
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          svgPath: .github/CONTRIBUTORS.svg
          affiliation: all
          includeBots: false
          excludeUsers: BeginCI snyk-bot
          avatarSize: 96
          userNameHeight: 20
          svgWidth: 830
          commitMessage: ':blue_heart: Updates contributor SVG'
    